[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "Setuptools.build_meta"

[project]
name = "cosmology_amilly"
version = "0.0.1"
authors = [{ name = "Shuyan Wang", email = "amillyforph@outlook.com" }]
description = "A Python package for cosmology calculations"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Intended Audience :: Science/Research",
]

[project.urls]
Homepage = "https://github.com/AmillyW/MyCosmoPy"
# Documentation = "https://cosmology-toolkit.readthedocs.io"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
cosmology = ["data/*.dat"]

[project.optional-dependencies]
test = ["pytest>=6.0", "pytest-cov"]
docs = ["sphinx>=4.0", "nbsphinx"]
